# Generated by Django 2.1.2 on 2018-10-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(blank=True, default='', max_length=100)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(blank=True, default='', max_length=60)),
                ('user_review', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ('review_date',),
            },
        ),
    ]
