# Generated by Django 2.1.2 on 2018-10-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20181009_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
