# Generated by Django 2.1.2 on 2019-02-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20181009_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
